### ISSUE TITLE
Sponsored Brands Title Authority Validation is now available in the Amazon Advertising API

### ISSUE THREAD

**Issue by moltar** [ScaleLeap/amazon-advertising-api-sdk#468]
Title Authority Validation, which prevents repetitive images from appearing in Sponsored Brands (SB) book campaigns, is now available in the SB API for advertisers in the United States. SB campaigns require advertisers to select three ASINs, and for book campaigns, those ASINs must be associated with different titles to avoid displaying repetitive products in the same ad. For more information, see the reference documentation.

https://advertising.amazon.com/API/docs/en-us/info/release-notes?order=44

https://advertising.amazon.com/API/docs/en-us/info/release-notes

**Comment by nguyentoanit** [comment]
@moltar : This issue seems to make from a release note bot? Do i need to resolve them now?

**Comment by moltar** [comment]
Not for now, as I think I don't have access yet.
