### ISSUE TITLE
Sponsored Display product targeting is now available for US sellers on the Amazon Advertising API

### ISSUE THREAD

**Issue by moltar** [ScaleLeap/amazon-advertising-api-sdk#483]
Sponsored Display (beta) product targeting is now available in the Amazon Advertising API for sellers in the US. This functionality was previously available for vendors and is now available for professional sellers enrolled in the Amazon Brand Registry (https://brandservices.amazon.com/). Product targeting for Sponsored Display gives sellers additional opportunities to reach and re-engage audiences in combination with Views audiences. Product targeting enables advertisers to promote product discovery, measure campaigns more effectively by targeting specific products or relevant product categories on Amazon, and gain greater line of sight into campaign optimization. Sellers now have the ability to: target multiple ASINs within campaigns, access detailed reporting, leverage flexible bidding options, and broaden category targeting capabilities. Product targeting in Sponsored Display brings audiences closer to the point of purchase and helps brands stay top of mind. Product targeting ads may appear alongside product description pages, customer reviews, shopping results pages, or under the featured offer.

https://advertising.amazon.com/API/docs/en-us/info/release-notes?order=38

https://advertising.amazon.com/API/docs/en-us/info/release-notes

**Comment by moltar** [comment]
Please look into this, and if it is available now via the API.

But even if not, please implement this just using the docs, without Polly, if sandbox does not have data.

Thanks.

**Comment by nguyentoanit** [comment]
@moltar :
in my opinion:
- Sponsored Display product targeting the docs mention is [Targeting API](https://advertising.amazon.com/API/docs/en-us/sponsored-display/3-0/openapi#/Targeting)?. I just want confirm before implementing

When use these APIs we need have SD campaigns, adgroups, etc. It's still fine when our sdk doesn't support to create them?
