### ISSUE TITLE
Oauth expects type MarketPlace but amazonMarketplaces returns type AmazonMarketplace

### ISSUE THREAD

**Issue by amazonadpro** [ScaleLeap/amazon-advertising-api-sdk#590]
Example listed here does not work: https://github.com/ScaleLeap/amazon-advertising-api-sdk/tree/master/docs#oauth2

![image](https://user-images.githubusercontent.com/71645724/94148824-bc5e2200-fe3c-11ea-892b-3461e471c63a.png)

![image](https://user-images.githubusercontent.com/71645724/94148897-d6980000-fe3c-11ea-9709-934f0a208bba.png)

**Comment by moltar** [comment]
@amazonadpro that is because some marketplaces do not have advertising.

You may use a utility function to guard against that: https://github.com/ScaleLeap/amazon-marketplaces#utility-functions

```
// TypeScript assertion function that ensures that the marketplace has advertising enabled.
// Throws if not.
assertMarketplaceHasAdvertising(amazonMarketplaces.US)
// now the marketplace guaranteed to have advertising and will pass type check
```

**Comment by moltar** [comment]
@nguyentoanit can you please fix the docs to include that?

**Comment by moltar** [comment]
@amazonadpro here's a working example btw, and see the examples dir for more

https://github.com/ScaleLeap/amazon-advertising-api-sdk/blob/master/examples/auth.ts

**Comment by amazonadpro** [comment]
Hey @moltar thanks, although that example seems to be for generating the HTTP Client. I'm trying to generate the OAuthClient to get the Token + Scope that is then used in the example above. 

`  const redirectUri = 'example.com'
const client = new OAuthClient(
    {
      clientId: process.env.AMAZON_CLIENT_ID,
      clientSecret: process.env.AMAZON_CLIENT_SECRET,
      redirectUri,
    },
    amazonMarketplaces.GB
  );`

**Comment by amazonadpro** [comment]
In 1.23

**Comment by amazonadpro** [comment]
![image](https://user-images.githubusercontent.com/71645724/94180668-f858ad80-fe63-11ea-960d-c8b79fe516bb.png)

**Comment by moltar** [comment]
Here you go, I added an OAuth example: https://github.com/ScaleLeap/amazon-advertising-api-sdk/blob/master/examples/o-auth.ts

**Comment by moltar** [comment]
Also, in `client.getToken(uri)` -- the URI here is the URI that the user was redirected to. As in, "the current request URI", e.g. from Express or another framework.

That URI should contain `?token=....` string.

**Comment by amazonadpro** [comment]
@moltar Thank you very much I'll give that a go now.
