### ISSUE TITLE
View Customer Search Term Campaign Breakdown

### ISSUE THREAD

**Issue by amazonadpro** [ScaleLeap/amazon-advertising-api-sdk#594]
Say I have a **BROAD** Campaign for `paint pens`

How can I view the campaign breakdown of all the different search terms that the advert was shown under. 

eg
Black paint pens
White paint pens 

and then lastly view the clicks, impressions, cost, etc of the individual search terms. 

Thanks!

**Comment by moltar** [comment]
Hey @amazonadpro,

I am sorry, but we cannot provide support for Amazon Advertising API. Please refer to the docs, and if that does not cover it, then please ask Amazon directly via the Jira channel.

Also, note that not all use cases might be covered by this SDK.

**Comment by amazonadpro** [comment]
@moltar No worries, thanks for creating such a great SDK anyway :)
