### ISSUE TITLE
AccessToken and client ID

### ISSUE THREAD

**Issue by kodeine** [ScaleLeap/amazon-advertising-api-sdk#609]
So on seller central i get `Developer ID`, `AWS Access Key ID`, `Client secret`. Now can you tell me where do i get the scope and client id? Do i need to use oauth?

I am trying to use this in a CLI app.
 
```
const auth = {
  accessToken: 'Atza|IQEBLjAsAhRmHjNgHpi0U...',
  clientId: 'amzn1.application-oa2-client.a8358a60...',
  scope: 1234567890,
}
```

**Comment by kodeine** [comment]
Also, how did you setup redirectUri on a local machine?

**Comment by moltar** [comment]
> So on seller central i get `Developer ID`, `AWS Access Key ID`, `Client secret`. Now can you tell me where do i get the scope and client id? Do i need to use oauth?
> 
> I am trying to use this in a CLI app.
> 
> ```
> const auth = {
>   accessToken: 'Atza|IQEBLjAsAhRmHjNgHpi0U...',
>   clientId: 'amzn1.application-oa2-client.a8358a60...',
>   scope: 1234567890,
> }
> ```

Please refer to the [official documentation](https://advertising.amazon.com/API/docs/en-us/setting-up/generate-api-tokens), it is already well explained there.

> Also, how did you setup redirectUri on a local machine? i am assuming `ngrok` here to the rescue?

This is outside the scope of the package.

You can use `ngrok`. You also can setup a redirect to `localhost`.
