### ISSUE TITLE
in Get Reports, reportDate is not a range?

### ISSUE THREAD

**Issue by kodeine** [ScaleLeap/amazon-advertising-api-sdk#624]
Hello,
So i am getting reports but i wanted to ask if date range is accepted instead of one day? if i want last 60 days i have to loop through, api doesn't let ranges defined or am i missing something?

**Comment by moltar** [comment]
The API is documented here: https://advertising.amazon.com/API/docs/en-us/sponsored-products/2-0/openapi#/Reports

It has no native ability to specify range.
