### ISSUE TITLE
Httpclient intercept

### ISSUE THREAD

**Issue by kodeine** [ScaleLeap/amazon-advertising-api-sdk#628]
To work around the throttle error is there a possibility to intercept the http client module to handle errors and retries?

**Comment by moltar** [comment]
I recommend to use a higher level abstraction, such as [p-retry](https://github.com/sindresorhus/p-retry). 

The `ThrottlingError` class is [being exported,](https://github.com/ScaleLeap/amazon-advertising-api-sdk/blob/724db7a5b04d6210d520819253312ece6d9db1dc/src/errors.ts#L54) which you can then use to detect the throttling errors.

```ts
if (err instanceof ThrottlingError) {
  // handle throttling error
}
```

---

However, if you insist on having your own HTTP client, then you can sub-class `HttpClient`, override `request` method and pass it to `OperationProvider` by hand, then instantiate all of the operations manually.

See: https://github.com/ScaleLeap/amazon-advertising-api-sdk/blob/724db7a5b04d6210d520819253312ece6d9db1dc/src/amazon-advertising.ts#L40-L51

**Comment by kodeine** [comment]
Thank you, ill close this issue now.

**Comment by kodeine** [comment]
@moltar can we make operationProvider property in amazon advertising class protected? This way i can extend it easily

**Comment by moltar** [comment]
@kodeine Please create separate issues for new issues 😊

**Comment by moltar** [comment]
> @moltar can we make operationProvider property in amazon advertising class protected? This way i can extend it easily

What is the use case for that?
