### ISSUE TITLE
Converting circular structure to JSON

### ISSUE THREAD

**Issue by ownagedj** [ScaleLeap/amazon-advertising-api-sdk#643]
When calling the `SponsoredProductsReportOperation.getReport()` method, the client can run into an exception where it tries to JSON.stringify() the full response object, resulting in `Converting circular structure to JSON`

See: https://github.com/ScaleLeap/amazon-advertising-api-sdk/blob/master/src/http-client.ts#L87

Node: v14.14.0
Package Version: 1.30.9

```
"message": "Converting circular structure to JSON\n    --> starting at object with constructor 'ClientRequest'\n    |     property 'socket' -> object with constructor 'TLSSocket'\n    --- property '_httpMessage' closes the circle",
"stack": [
  {
    "filename": null,
    "function": null,
    "line": null
  },
  {
    "filename": null,
    "function": "stringify",
    "line": null
  },
  {
    "filename": "@scaleleap/amazon-advertising-api-sdk/lib/http-client.js",
    "function": "handleApiResponse",
    "line": 62
  },
  {
    "filename": "@scaleleap/amazon-advertising-api-sdk/lib/http-client.js",
    "function": "apiRequest",
    "line": 85
  }
```

The response of the api is the following

```
...
      host: [ 'Host', 'advertising-api-eu.amazon.com' ]
    }
  },
  data: 'Number of requests exceeded maximum allowed request rate.'
}
```

**Comment by moltar** [comment]
Do you have an example of a request that causes this issue? Thanks!

**Comment by ownagedj** [comment]
Unfortunately not. 
Just call the method until you run into the rate limit of Amazon.

**Comment by moltar** [comment]
Ok, so this happens on _any_ request, but only when it gets throttled?

**Comment by moltar** [comment]
@nguyentoanit please look at this. I am also experiencing this issue.

**Comment by moltar** [comment]
@ownagedj do you know which endpoint causes this?

Seems like `data` is not a well defined object, as documented, but instead it is a simple string:

```
Number of requests exceeded maximum allowed request rate.
```

Can you confirm that?

Thanks.

**Comment by moltar** [comment]
@ownagedj did you have time to test the new version?
