### ISSUE TITLE
oAuthClient.createToken RangeError: Invalid time value

### ISSUE THREAD

**Issue by kodeine** [ScaleLeap/amazon-advertising-api-sdk#685]
So i am trying the following and i get the invalid time value error.

```
const genToken = this.oAuthClient(marketplace)
      .createToken(token.accessToken, token.refreshToken);


  oAuthClient(marketplace: string) {
    return new OAuthClient({
        clientId: this.config.get<string>('AMAZON_CLIENT_ID'),
        clientSecret: this.config.get<string>('AMAZON_CLIENT_SECRET') ,
        redirectUri: this.config.get<string>('AMAZON_CALLBACK_URL'),
      },
      amazonMarketplaces[marketplace] as any,
    );
  }
```

```
    at node:internal/per_context/primordials:23:32
    at formatValue (node:internal/util/inspect:774:19)
    at formatProperty (node:internal/util/inspect:1689:11)
    at formatRaw (node:internal/util/inspect:1017:9)
    at formatValue (node:internal/util/inspect:803:10)
    at inspect (node:internal/util/inspect:336:10)
    at formatWithOptionsInternal (node:internal/util/inspect:2006:40)
    at formatWithOptions (node:internal/util/inspect:1888:10)
[ERROR] 11:18:21 RangeError: Invalid time value

```

**Comment by moltar** [comment]
@kodeine are you sure the error is coming from this package? The strack trace isn't complete, I think.

This error seems to be coming from the `Date` object, yet we are not using the `Date` object directly anywhere in the `OAuthClient` code.

Please provide more context or better yet a reproduction.

Thanks.

**Comment by kodeine** [comment]
It's surprising because I looked at the code and I didn't see anything with the date. But as soon I call that method I get that error. I am using mongodb but I commented it out but still get that error and only on that method, other methods works just fine.

**Comment by moltar** [comment]
@kodeine can you create a small, isolated reproduction repo for this, please? Feel free to comment out your credentials, ofc. I can test with mine.

**Comment by kodeine** [comment]
Sure, thank you for prompt responses

**Comment by kodeine** [comment]
@moltar i think i found the issue.
Following is the output of `OAuthClient`, notice the `expires` property. Maybe we need to keep expires as null if its invalid date? 

```
ClientOAuth2Token {
  client: <ref *1> ClientOAuth2 {
    options: {
      clientId: 'amzn1.application-oa2-client...',
      clientSecret: '......',
      redirectUri: 'http://localhost:4000/auth/amazon/callback',
      accessTokenUri: 'https://api.amazon.com/auth/o2/token',
      authorizationUri: 'https://www.amazon.com/ap/oa',
      scopes: [Array]
    },
    request: [AsyncFunction: request],
    code: CodeFlow { client: [Circular *1] },
    token: TokenFlow { client: [Circular *1] },
    owner: OwnerFlow { client: [Circular *1] },
    credentials: CredentialsFlow { client: [Circular *1] },
    jwt: JwtBearerFlow { client: [Circular *1] }
  },
  data: {
    access_token: 'Atza|...',
    refresh_token: 'Atzr|...',
    token_type: 'bearer'
  },
  tokenType: 'bearer',
  accessToken: 'Atza|-....',
  refreshToken: 'Atzr|....',
  expires: Invalid Date
}

```

**Comment by kodeine** [comment]
test project is at https://github.com/kodeine/test-proj

**Comment by moltar** [comment]
Hey @kodeine but it is not clear how to reproduce the failure? Can you please include the steps / commands / calls that I need to make to get the error? When I started nest and hit the endpoint it worked fine and dumped the same as above. At which point does it fail tho?

**Comment by kodeine** [comment]
@moltar please pull from test repo again i've updated the files to show error. looks like when mongodb is added then this error shows up

**Comment by moltar** [comment]
@nguyentoanit please look into this

**Comment by nguyentoanit** [comment]
Hi @kodeine:
Is there any reason you have to convert `ClientOAuth2.Token` instance to string?

We used [`client-oauth2`](https://www.npmjs.com/package/client-oauth2) package without default TTL configuration.
Therefore, [`expires` will be set to `Invalid Date` ](https://github.com/mulesoft-labs/js-client-oauth2/blob/68d2a71565641d321148798d7df9d78a3182e584/src/client-oauth2.js#L307)
When you convert, will get an error like above.

I took a look into [Access token in RFC docs](https://tools.ietf.org/html/rfc6749#page-10:~:text=1.4.%20%20Access%20Token,-Access) too. They don't mention about a default TTL for access token?
@moltar : Should we set default TTL when initial `OAuthClient`?

@kodeine: You can try to set TTL with `expiresIn` for token to resolve this issue?
```ts
const genToken = this.oAuthClient(marketplace).createToken(token.accessToken, token.refreshToken)
const duration: number = 100

genToken.expiresIn(duration)
console.log('genToken', genToken)
```

**Comment by moltar** [comment]
>  @moltar : Should we set default TTL when initial OAuthClient?

TBH I am not sure.

---

I am unable to reproduce the same issue.

I am wondering why does Mongo introduction causes this error? Does Mongo lib monkey patches some JS core libs, like Date?

@nguyentoanit are you able to repro this reliably on your end?

**Comment by kodeine** [comment]
I think we should setup default ttl based on amazon. As far i recall amazon token has one hour expiry so maybe we can set that value and does this mean expired() method didnt work before?

**Comment by moltar** [comment]
But what if you are instantiating a token from storage and the token is already aged? I don't understand why TTL needs to be there at all. I don't understand what is even the use case for having that TTL? OAuth process does not require this TTL anywhere.

**Comment by nguyentoanit** [comment]
@moltar: 
> I am unable to reproduce the same issue.
>
> I am wondering why does Mongo introduction causes this error? Does Mongo lib monkey patches some JS core libs, like Date?
>
> @nguyentoanit are you able to repro this reliably on your end?

Here is the stack trace in my local machine
```
RangeError: Invalid time value
    at Date.toISOString (<anonymous>)
    at Date.<computed> (D:\toannguyen\github\test\test-proj\node_modules\@mikro-orm\mongodb\MongoConnection.js:220:29)
    at formatValue (internal/util/inspect.js:550:31)
    at formatProperty (internal/util/inspect.js:1371:11)
    at formatRaw (internal/util/inspect.js:761:9)
    at formatValue (internal/util/inspect.js:567:10)
    at inspect (internal/util/inspect.js:221:10)
    at formatWithOptions (internal/util/inspect.js:1656:40)
    at Object.Console.<computed> (internal/console/constructor.js:272:10)
    at Object.log (internal/console/constructor.js:282:61)
```

I followed these steps to reproduce:
1. Build docker container from docker-compose.yml
2. Install dependencies and run app with debug mode: `npm run start:debug`
3. Open browser and go to http://localhost:4444

**Comment by nguyentoanit** [comment]
@kodeine : 
> I think we should setup default ttl based on amazon. As far i recall amazon token has one hour expiry so maybe we can set that value

[The docs](https://advertising.amazon.com/API/docs/en-us/setting-up/generate-api-tokens#Step-5:-Call-the-authorization-URL-to-request-authorization-and-refresh-tokens:~:text=Note%20that%20authorization%20tokens%20are%20valid,expire.%20Refresh%20tokens%20do%20not%20expire.) mentioned them too:
> Note that authorization tokens are valid for 60 minutes and must refreshed using the refresh token once they expire. Refresh tokens do not expire.

---

>does this mean expired() method didnt work before?

If you didn't set an expiration. `expired()` always returns `false`
```ts
function expired () {
  const expires = new Date("foo") // Invalid Date
  return Date.now() > expires.getTime() // undefined
}
```

Ref: https://github.com/mulesoft-labs/js-client-oauth2/blob/68d2a71565641d321148798d7df9d78a3182e584/src/client-oauth2.js#L398

**Comment by moltar** [comment]
We are just wrapping the `createToken` method from `client-oauth2`, which does not have a way to set the token expiration. You can, however, set that on the Token object yourself, once you get the token. The thing is, we cannot set it by default, because token can be retrieved from the database, which is already expired or almost expired.

**Comment by kodeine** [comment]
Okay so the token is not to be stored in database or data stores other than cache. Refresh tokens are stored in datastores since refresh tokens never expire. So when we create a token from refresh we should enable a default ttl of 1 hr each time. Cache just checks if token is valid or not based on ttl.

**Comment by moltar** [comment]
> so the token is not to be stored in database

Why not? We store tokens in the database (encrypted). So that they can be shared across processors.

If there are 50 workers running 10 jobs per minute, it's wasteful to refresh the token on each request. So we "cache" them in the database. Then there is a separate process that runs every 55 minutes and refreshes the token and updates the database entry.
