### ISSUE TITLE
recordType could be wrong

### ISSUE THREAD

**Issue by guillim** [ScaleLeap/amazon-advertising-api-sdk#687]
Hello,

First, your project is great, go on : it really helps to understand the Amz adv API. On my side, I am trying to use it for reporting (only). 

However, I am encountering some issue with **Sponsored Brands** report request :

Are these recordType options corrects ? Sounds like undefined to me when trying...
https://github.com/ScaleLeap/amazon-advertising-api-sdk/blob/f519825f2fb513a75f5bd6af99116d44ebc9efc3/src/operations/reports/report-types.ts#L23-L25

I have error message like :
> Could not find resource for full path: https://advertising-api-eu.amazon.com/v2/hsa/headlineSearch/report

**Comment by nguyentoanit** [comment]
Hi, @guillim
I confirmed your issue with `headlineSearch` and `searchTerms` report type (resolved in https://github.com/ScaleLeap/amazon-advertising-api-sdk/pull/689).
But, I couldn't reproduce with `targets` from sandbox API.

Could you please to show more info?
