### ISSUE TITLE
TypeError: Cannot read property 'region' of undefined

### ISSUE THREAD

**Issue by kodeine** [ScaleLeap/amazon-advertising-api-sdk#730]
Looks like some of the marketplaces dont have `region` property. I think all these objects should be consistent.

```
 marketplace CN
TypeError: Cannot read property 'region' of undefined
    at new AmazonAdvertising (node_modules/@scaleleap/amazon-advertising-api-sdk/src/amazon-advertising.ts:45:75)
```

**Comment by moltar** [comment]
Some marketplaces do not have advertising at all. And those marketplaces do not have the entire `advertising` prop.

The `@scaleleap/amazon-marketplaces` package has an assertion (and type guarding, if you are using TS) utility function for that.

https://github.com/ScaleLeap/amazon-marketplaces/blob/4322553758592b2e13b2386d72cdd20449604e0c/src/utils.ts#L42

You may find the full list of marketplaces that have advertising here: https://advertising.amazon.com/API/docs/en-us/get-started/how-to-use-api
