### ISSUE TITLE
Not able to access NegativeTargeting api for Sponsored Displays

### ISSUE THREAD

**Issue by ankushsood17** [ScaleLeap/amazon-advertising-api-sdk#837]
I am not able to access Negative Targeting data for Sponsored Displays. Whenever I call the API, the route which the function call is as mentioned below.

error: ResourceNotFoundError: Could not find resource for full path: https://advertising-api-eu.amazon.com/v2/sd/negativeTargetsv2/sd/negativeTargets/extended

Solution:
In path:

https://github.com/ScaleLeap/amazon-advertising-api-sdk/blob/master/src/operations/negative-targeting/sponsored-display-negative-targeting-operation.ts

Line no 89.

**this.paramsFilterTransformer(`${this.resource}/extended`, params)
should be replaced with
this.paramsFilterTransformer(`/extended`, params),**

**Comment by moltar** [comment]
@ankushsood17 please open a PR
