### ISSUE TITLE
Is it possible to get accessToken through refreshToken?

### ISSUE THREAD

**Issue by bytrix** [ScaleLeap/amazon-advertising-api-sdk#899]
HttpClientAuth only provides accessToken but there is no refreshToken, how can I get accessToken with refreshToken?
https://github.com/ScaleLeap/amazon-advertising-api-sdk/blob/92379fc6f7ab78c58279a29ab4701a70d9079950/src/http-client.ts#L11

**Comment by bytrix** [comment]
I have a problem, if someone already login at his client, and then he send me a refreshToken, how can I get accessToken with this refreshToken?

**Comment by bytrix** [comment]
As Amazon docs mentioned, to retrieve a new access token, just pass the refresh token:
https://advertising.amazon.com/API/docs/en-us/get-started/generate-api-tokens
```
curl \
    -X POST \
    -H "Content-Type:application/x-www-form-urlencoded;charset=UTF-8" \
    --data "grant_type=refresh_token&client_id=YOUR_CLIENT_ID&refresh_token=YOUR_REFRESH_TOKEN&client_secret=YOUR_CLIENT_SECRET" \
    https://api.amazon.com/auth/o2/token
```

**Comment by moltar** [comment]
> HttpClientAuth only provides accessToken but there is no refreshToken

That's correct. Because `HttpClientAuth` is only concerned with making authorized calls to the API. And to make an authorised call to the API it does not need a refresh token, and only an access token.

> how can I get accessToken with refreshToken?

> As Amazon docs mentions, to retrieve a new access token, just pass the refresh token:

Yeah, you can just do that with any HTTP client library.
