### ISSUE TITLE
Can we download Amazon Sponsored display snapshots using ScaleLeap amazon-advertising-api-sdk?

### ISSUE THREAD

**Issue by sravyadalavai-vl** [ScaleLeap/amazon-advertising-api-sdk#902]

**Comment by moltar** [comment]
No yet.

Feel free to open a PR.

See https://github.com/ScaleLeap/amazon-advertising-api-sdk/tree/master/src/operations/snapshots

**Comment by sravyadalavai-vl** [comment]
So based on other snapshots. do I need to create a new file for sponsored display ?

**Comment by moltar** [comment]
Sure, similar to other ad types, create a file, and fill it according to API docs.

**Comment by sravya-yelleti** [comment]
please give access to push to feature branch

**Comment by moltar** [comment]
You need to fork and create a PR from your fork.

**Comment by moltar** [comment]
Closed via #914

**Comment by sravya-yelleti** [comment]
when will this be released?

**Comment by moltar** [comment]
Sorry, no idea why, but the release didn't trigger from the PR merge. It usually does automatically. I just manually triggered it. It has been released.

**Comment by sravya-yelleti** [comment]
Thank you
