### ISSUE TITLE
SponsoredDisplaySnapshotOperation not working as expected 

### ISSUE THREAD

**Issue by sravya-yelleti** [ScaleLeap/amazon-advertising-api-sdk#921]
getting this error
body: '"ops is not a constructor"'

**Comment by moltar** [comment]
Which file, line?

**Comment by sravya-yelleti** [comment]
src/operations/snapshots/sponsored-display-snapshot-operation.ts

**Comment by moltar** [comment]
@nguyentoanit please take a look tomorrow

**Comment by nguyentoanit** [comment]
@sravya-yelleti : It looks like a compile error from your site.
And I couldn't reproduce your error [here.](https://github.com/ScaleLeap/amazon-advertising-api-sdk/blob/test/sd-snapshot-operation/test/operations/snapshots/sponsored-display-snapshot-operation.test.ts)

We can request to [sandbox API](https://github.com/ScaleLeap/amazon-advertising-api-sdk/runs/5105543494?check_suite_focus=true#step:6:117) and get `GenericError: Internal Server Error`.

Could you please give me your sample code?

**Comment by sravya-yelleti** [comment]
I added the sponsored-display-snapshot-operation.ts because it was not there before.
 I think [https://github.com/ScaleLeap/amazon-advertising-api-sdk/pull/923] (https://github.com/ScaleLeap/amazon-advertising-api-sdk/pull/923) might fix it. please let me know if I missed anything.

**Comment by sravya-yelleti** [comment]
i'm still getting the same error "ops is not a constructor" for 
snapshotOperation = operationProvider.create(SponsoredDisplaySnapshotOperation);
SponsoredProductsSnapshotOperation is working as expected in the same code

**Comment by sravya-yelleti** [comment]
please let me know if i should make any changes

**Comment by sravya-yelleti** [comment]
I have been facing the same error when I try to create Sponsored Display Snapshot report request: “ops is not a constructor”

Here is the sample code:

const {
    SponsoredDisplaySnapshotOperation
} = require('@scaleleap/amazon-advertising-api-sdk');
let operationProvider = await amazonApiSdk.GetOperationProvider(secretName);
const profileOperation = operationProvider.create(ProfileOperation);
apiProfiles = await profileOperation.listProfiles();

apiProfiles.forEach(profile => {
    operationProvider.client.auth.scope = profile.profileId;
    snapshotOperation = operationProvider.create(SponsoredDisplaySnapshotOperation);
//getting error here
    response = await snapshotOperation.requestSnapshot(campaigns, {
        "stateFilter": "enabled,paused,archived"
    });
    reportId = response.snapshotId;
});

The same code is working fine for SponsoredProductsSnapshotOperation

**Comment by nguyentoanit** [comment]
@sravya-yelleti : this should be resolved after we merge PR #927. 👍
